INSERT INTO countries (code, name, name_ar) VALUES ('US', 'United States', 'الولايات المتحدة');
INSERT INTO countries (code, name, name_ar) VALUES ('GB', 'United Kingdom', 'المملكة المتحدة');
INSERT INTO countries (code, name, name_ar) VALUES ('FR', 'France', 'فرنسا');
INSERT INTO countries (code, name, name_ar) VALUES ('DE', 'Germany', 'ألمانيا');
INSERT INTO countries (code, name, name_ar) VALUES ('JP', 'Japan', 'اليابان');
INSERT INTO countries (code, name, name_ar) VALUES ('CN', 'China', 'الصين');
INSERT INTO countries (code, name, name_ar) VALUES ('IN', 'India', 'الهند');
INSERT INTO countries (code, name, name_ar) VALUES ('BR', 'Brazil', 'البرازيل');
INSERT INTO countries (code, name, name_ar) VALUES ('CA', 'Canada', 'كندا');
INSERT INTO countries (code, name, name_ar) VALUES ('SA', 'Saudi Arabia', 'السعودية');
INSERT INTO countries (code, name, name_ar) VALUES ('AE', 'United Arab Emirates', 'الإمارات العربية المتحدة');
INSERT INTO countries (code, name, name_ar) VALUES ('EG', 'Egypt', 'مصر');
INSERT INTO countries (code, name, name_ar) VALUES ('IQ', 'Iraq', 'العراق');
INSERT INTO countries (code, name, name_ar) VALUES ('JO', 'Jordan', 'الأردن');
INSERT INTO countries (code, name, name_ar) VALUES ('LB', 'Lebanon', 'لبنان');
INSERT INTO countries (code, name, name_ar) VALUES ('SY', 'Syria', 'سوريا');
INSERT INTO countries (code, name, name_ar) VALUES ('MA', 'Morocco', 'المغرب');
INSERT INTO countries (code, name, name_ar) VALUES ('DZ', 'Algeria', 'الجزائر');
INSERT INTO countries (code, name, name_ar) VALUES ('TN', 'Tunisia', 'تونس');
INSERT INTO countries (code, name, name_ar) VALUES ('YE', 'Yemen', 'اليمن');